export const ROLES = {
  CITIZEN: 'CITIZEN',
  CONTROL_ROOM_ADMIN: 'CONTROL_ROOM_ADMIN',
  STATION_HEAD: 'STATION_HEAD',
  INVESTIGATING_OFFICER: 'INVESTIGATING_OFFICER',
  FIELD_OFFICER: 'FIELD_OFFICER'
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED'
};

export const DUTY_STATUS = {
  ON_DUTY: 'ON_DUTY',
  OFF_DUTY: 'OFF_DUTY',
  BUSY: 'BUSY',
  AVAILABLE: 'AVAILABLE',
  RESPONDING: 'RESPONDING'
};

export const OFFICER_RANKS = {
  COMMISSIONER: 'COMMISSIONER',
  INSPECTOR: 'INSPECTOR',
  SUB_INSPECTOR: 'SUB_INSPECTOR',
  ASSISTANT_SUB_INSPECTOR: 'ASSISTANT_SUB_INSPECTOR',
  HEAD_CONSTABLE: 'HEAD_CONSTABLE',
  CONSTABLE: 'CONSTABLE'
};

export const STATION_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

export const CRIME_TYPES = {
  THEFT: 'THEFT',
  ASSAULT: 'ASSAULT',
  FRAUD: 'FRAUD',
  CYBER_CRIME: 'CYBER_CRIME',
  HARASSMENT: 'HARASSMENT',
  MISSING_PERSON: 'MISSING_PERSON',
  VANDALISM: 'VANDALISM',
  TRAFFIC: 'TRAFFIC',
  OTHER: 'OTHER'
};

export const COMPLAINT_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

export const COMPLAINT_STATUS = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ASSIGNED: 'ASSIGNED',
  INVESTIGATION: 'INVESTIGATION',
  FIR_REGISTERED: 'FIR_REGISTERED',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED'
};

export const FIR_STATUS = {
  REGISTERED: 'REGISTERED',
  UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
  CHARGESHEET_FILED: 'CHARGESHEET_FILED',
  CLOSED: 'CLOSED'
};

export const SOS_STATUS = {
  ACTIVE: 'ACTIVE',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  DISPATCHED: 'DISPATCHED',
  EN_ROUTE: 'EN_ROUTE',
  ARRIVED: 'ARRIVED',
  RESOLVED: 'RESOLVED',
  ESCALATED: 'ESCALATED',
  REJECTED: 'REJECTED'
};

export const ANNOUNCEMENT_TYPES = {
  CRIME_ALERT: 'CRIME_ALERT',
  ROAD_ALERT: 'ROAD_ALERT',
  MISSING_PERSON: 'MISSING_PERSON',
  PUBLIC_SAFETY: 'PUBLIC_SAFETY',
  GENERAL: 'GENERAL'
};

export const ANNOUNCEMENT_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

export const ANNOUNCEMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  ARCHIVED: 'ARCHIVED'
};

export const PATROL_STATUS = {
  PLANNED: 'PLANNED',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

export const NOTIFICATION_TYPES = {
  COMPLAINT: 'COMPLAINT',
  FIR: 'FIR',
  SOS: 'SOS',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  PATROL: 'PATROL',
  SYSTEM: 'SYSTEM'
};

export const SUSPECT_STATUS = {
  SUSPECT: 'SUSPECT',
  ACCUSED: 'ACCUSED',
  CONVICTED: 'CONVICTED',
  ACQUITTED: 'ACQUITTED',
  DISCHARGED: 'DISCHARGED'
};

export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  CASE_CREATED: 'CASE_CREATED',
  CASE_UPDATED: 'CASE_UPDATED',
  OFFICER_ASSIGNED: 'OFFICER_ASSIGNED',
  FIR_REGISTERED: 'FIR_REGISTERED',
  EVIDENCE_ADDED: 'EVIDENCE_ADDED',
  SUSPECT_CREATED: 'SUSPECT_CREATED',
  SUSPECT_UPDATED: 'SUSPECT_UPDATED',
  SOS_CREATED: 'SOS_CREATED',
  SOS_ACKNOWLEDGED: 'SOS_ACKNOWLEDGED',
  SOS_DISPATCHED: 'SOS_DISPATCHED',
  SOS_EN_ROUTE: 'SOS_EN_ROUTE',
  SOS_ARRIVED: 'SOS_ARRIVED',
  SOS_REJECTED: 'SOS_REJECTED',
  SOS_ESCALATED: 'SOS_ESCALATED',
  SOS_RESOLVED: 'SOS_RESOLVED',
  OFFICER_LOCATION_UPDATED: 'OFFICER_LOCATION_UPDATED',
  PATROL_STARTED: 'PATROL_STARTED',
  PATROL_PAUSED: 'PATROL_PAUSED',
  PATROL_COMPLETED: 'PATROL_COMPLETED',
  CASE_RESOLVED: 'CASE_RESOLVED'
};
